/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "amzmhayigswqdlarujow"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtem1oYXlpZ3N3cWRsYXJ1am93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNDY3ODMsImV4cCI6MjA3NzYyMjc4M30.i2xR0my4M75d3M-QGHcWMsW-fzTsIfqDM7QUR-Wxzsc"